### ISSUE TITLE
No Elevation Data 

### ISSUE THREAD

**Issue by fakeart** [SimBlocks/OneWorldSDKforUnity#12]
I made the installation according to the tutorial. But I have no elevation on the map. What could be the problem?

![image](https://user-images.githubusercontent.com/23584686/148480377-8e550cb5-9986-4461-9557-8c3e3373d3e9.png)

**Comment by fakeart** [comment]
Very strange behavior of many parts of the map. In most cases, there are no elevation data at all. 

![image](https://user-images.githubusercontent.com/23584686/148482580-8155c442-80c6-4b6d-8304-31b02acc60a3.png)

**Comment by SimBlocks** [comment]
Was the default configuration file used in these two images along with a valid Bing Maps key, or were similar configuration changes made as in the issue below?
https://github.com/SimBlocks/OneWorldSDKforUnity/issues/7

**Comment by fakeart** [comment]
The screenshot below shows the default configuration file. The problem is identical.

![image](https://user-images.githubusercontent.com/23584686/148536150-308ee474-dc2d-42cc-90e3-85dee99ba852.png)

How can I get the quality of the map like in your screenshot?

![image](https://user-images.githubusercontent.com/23584686/148536599-cb0933e1-98da-494a-9d95-4e906d9723ef.png)

**Comment by MrPringles801** [comment]
I am having the same problem is there anything new on this issue? I have restarted the project multiple times following the tutorial to the letter and every time it works until zooming in at which point it fails to use elevation maps.

**Comment by fakeart** [comment]
No, I didn't find a solution.

**Comment by SimBlocks** [comment]
Thank you for reporting this issue. We will have one of our developers take a look.

**Comment by federal1789** [comment]
The brute force solution is that the code at line number 77 in the BingElevationProvider.cs for free bing key
`//On failure, zero out the points
 for (var i = startIdx; i < endIdx; ++i)
 {
      var pos = ary[i].Position;
      ary[i] = new ElevationPointSample(pos, 0);
 }` 
take comment then write new code line in same section
`await QueryPointSamplesAsyncInto(points, tok);` 
it is mean, if bing not response or give some error, it tries to collect elevation data

**Comment by SimBlocks** [comment]
Thank you. If there is a failure retrieving the data, should we attempt to restore or query data from a previous lower LOD?


Jordan Dauble

SimBlocks LLC, Owner

407-641-5218

3259 Progress Drive, Ste 140, Orlando, FL 32826

[cid:56b74d18-eb14-464e-aced-edff30f86f51]<http://www.simblocks.io>

[1511036968179_LinkedIn.png]<https://www.linkedin.com/company/simblocks-llc> [1511036994097_Twitter.png] <http://twitter.com/SimBlocks>  [1511036982870_Facebook.png] <https://www.facebook.com/simblocks/>  [1511036999862_YouTube.png] <https://www.youtube.com/simblocksio/videos>

Chair, SISO CIGI PSG<https://www.sisostds.org/StandardsActivities/SupportGroups/CIGIPSG-CommonImageGeneratorInterface.aspx>

________________________________

**Comment by SimBlocks** [comment]
Hello, please confirm if you are still seeing this elevation issue with the latest code.
