### ISSUE TITLE
after outputting to exe, an error will be reported when running

### ISSUE THREAD

**Issue by qiaonifengxue** [SimBlocks/OneWorldSDKforUnity#13]
Error assigning 2DArray texture to 2D texture property '_MainTex': Dimensions must match
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.Material:SetTexture (string,UnityEngine.Texture)
UnityEngine.Material:set_mainTexture (UnityEngine.Texture)
sbio.owsdk.Unity.TerrainTileChunker/TileAtlasInfo:.ctor (int,byte,UnityEngine.Shader,UnityEngine.Shader,bool) (at D:/we/OneWorldSDKforUnity-main/src/OneWorldSDK_UnityDemo/Assets/Scripts/TerrainTileChunker.cs:1564)
sbio.owsdk.Unity.TerrainTileChunker:.ctor (sbio.owsdk.Unity.TerrainTileChunker/Settings,UnityEngine.Shader,UnityEngine.Shader,sbio.owsdk.IWorldContext,sbio.owsdk.Unity.TileLoadContext,sbio.owsdk.Services.ITileMeshProvider) (at D:/we/OneWorldSDKforUnity-main/src/OneWorldSDK_UnityDemo/Assets/Scripts/TerrainTileChunker.cs:720)
sbio.OneWorldSDKViewer.WorldChunker:Start () (at D:/we/OneWorldSDKforUnity-main/src/OneWorldSDK_UnityDemo/Assets/UnityDemo/Scripts/WorldChunker.cs:31)

[D:/we/OneWorldSDKforUnity-main/src/OneWorldSDK_UnityDemo/Assets/Scripts/TerrainTileChunker.cs line 1564]

Error assigning 2DArray texture to 2D texture property '_MainTex': Dimensions must match
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.Material:SetTexture (string,UnityEngine.Texture)
UnityEngine.Material:set_mainTexture (UnityEngine.Texture)
sbio.owsdk.Unity.TerrainTileChunker/TileAtlasInfo:.ctor (int,byte,UnityEngine.Shader,UnityEngine.Shader,bool) (at D:/we/OneWorldSDKforUnity-main/src/OneWorldSDK_UnityDemo/Assets/Scripts/TerrainTileChunker.cs:1564)
sbio.owsdk.Unity.TerrainTileChunker:.ctor (sbio.owsdk.Unity.TerrainTileChunker/Settings,UnityEngine.Shader,UnityEngine.Shader,sbio.owsdk.IWorldContext,sbio.owsdk.Unity.TileLoadContext,sbio.owsdk.Services.ITileMeshProvider) (at D:/we/OneWorldSDKforUnity-main/src/OneWorldSDK_UnityDemo/Assets/Scripts/TerrainTileChunker.cs:720)
sbio.OneWorldSDKViewer.WorldChunker:Start () (at D:/we/OneWorldSDKforUnity-main/src/OneWorldSDK_UnityDemo/Assets/UnityDemo/Scripts/WorldChunker.cs:31)

[D:/we/OneWorldSDKforUnity-main/src/OneWorldSDK_UnityDemo/Assets/Scripts/TerrainTileChunker.cs line 1564]

**Comment by qiaonifengxue** [comment]
Well, I forgot to drag the data folder。

**Comment by SimBlocks** [comment]
Thanks, is this working now?

**Comment by qiaonifengxue** [comment]
> Thanks, is this working now?

Yes, it's normal
