### ISSUE TITLE
Errors related to the DLLs after sample scene setup

### ISSUE THREAD

**Issue by petriw** [SimBlocks/OneWorldSDKforUnity#21]
Hi, I'm getting the following errors once I have built the SDK (in Library) and copied the DLLs using the bat file.
These show on project load and if I press play in any scene.
![image](https://user-images.githubusercontent.com/140110/185607653-ffbb6c18-7e24-4922-b677-7e9184837c91.png)

Thanks!

**Comment by SimBlocks** [comment]
Hello @petriw, thank you for reporting this issue. Please see the latest commit for a fix.

**Comment by petriw** [comment]
Thank you, this solved it! :)
