### ISSUE TITLE
Error in built program of Unity

### ISSUE THREAD

**Issue by CharlesQHappy** [SimBlocks/OneWorldSDKforUnity#5]
Hi, When I built Unity,  the build program give me errors in the attached image, and I can't see the Earth. What could be wrong?

![errors](https://user-images.githubusercontent.com/54677365/137081801-95ad8cbf-9fda-4ec5-9695-832670c0e2c6.png)

**Comment by SimBlocks** [comment]
Hello, it looks like you have a null object while running the project in Unity, specifically with the main scripts related to the One World SDK for Unity. Do you have this issue with an unmodified clone of the repository? Also, could you please check if the OneWorldSDK Viewer game object has these variables set in the Inspector? 
![OneWorldSDKViewer_Inspector](https://user-images.githubusercontent.com/82296340/137246788-14bdee2b-1f46-4b2d-841e-0ff201f7f863.PNG)

**Comment by CharlesQHappy** [comment]
Oh, somehow it worked after restarting the computer, strange though.
