### ISSUE TITLE
2 problems of creating offline map .

### ISSUE THREAD

**Issue by CharlesQHappy** [SimBlocks/OneWorldSDKforUnity#6]
I followed the document in https://github.com/SimBlocks/OneWorldSDKforUnity/blob/main/docs/ExternalData.md  to create offline imagery map.  I could see the big picture, but still had 2 small problems.

1.  How to traverse all the Geodetic2d point  of the whole Earth since it is a vector consisting of real numbers which has infinite amounts?
2. After I got the GeoBoundingBox with the function TileToBounds, how could I get the corresponding PNG or JPEG image?

**Comment by CharlesQHappy** [comment]
I changed the "Export"  function so it would only export images. But I found the code described in the following image didn't run because the "bbbbbbbbbbbbbb..." wasn't printed on the output window while the "aaaaaaaaaaaaaaaaaa...." was.  What was wrong ?
![Thread does not run](https://user-images.githubusercontent.com/54677365/139804527-92e0a9ea-0fcb-4750-bc1a-aa7efbd4b8f2.png)

**Comment by CharlesQHappy** [comment]
OK， I think I find a way to do that, I just traverse all the coordinate with a interval.

**Comment by SimBlocks** [comment]
Good job.
