### ISSUE TITLE
Many tiles without elevation data?

### ISSUE THREAD

**Issue by cneumann** [SimBlocks/OneWorldSDKforUnity#7]
I'm using the demo scene with a Bing basic/dev API key. Since the default configuration limits the maximum tile LOD to 10 I adjusted it as follows, adding the API key and increasing maxTileLOD to 16:

```jsonc
{
  //Settings for each elevation provider
  "elevationProviderSettings": {
    "bing": {
      //The bing API key to use
      "apiKey": "{MY_BING_API_KEY}"
  },

  // ... omit unchanged parts ...

  "tileChunkerSettings": {
    //The number of tiles that will be kept loaded in-cache at a time
    //Cached tiles don't have to be re-queried and are simply reactivated
    "numTiles": 4095,
    //The number of tiles to preload (load at startup)
    "preloadPercent": 0,
    "disablePhysics": false,
    //The number max number of tiles that will be loaded concurrently
    //Defaults to processor count
    "maxConcurrentLoad": null,
    //The LOD that features will be queried at
    "featureLoadLOD": 15,
    //The maximum LOD to create tiles at
    "maxTileLOD": 16,
    //The maximum lod to use for physics
    "maxPhysicsLOD": 10,
    //The maximum amount of time in milliseconds spend loading tiles each frame
    //Increasing this number lowers frame-rate in high-load scenarious but
    //decreases latency for loading tiles
    "loadFrameBudget": 3,
    //The size of each texture atlas, in tiles
    //The actual pixel size will be (size*size*256)
    "atlasTileSize": 1,
    //Set to true to compress textures during runtime
    //Compressing textures significantly reduces RAM usage but can cause regular frame drops
    "compressTextures": false
  },

  // ... omit unchanged parts ...
}
```

With these settings much higher resolution image tiles are loaded, but only a fraction of the tiles appear to have elevation data associated with them, making them stand out among lots of "flat" tiles:
![lake-tahoe-missing-elevation](https://user-images.githubusercontent.com/117979/138152116-edc322e6-ca6f-459e-a2b2-8fe40cf3da9b.png)

This image is from latitude 38.9819 longitude -119.8195 elevation 9802.8. Is this expected or am I missing a relevant setting in the configuration? Thanks!

**Comment by fakeart** [comment]
Have you found a solution to this problem?

**Comment by SimBlocks** [comment]
Hello, we currently do not recommend increasing the maximum LOD values when using a Basic Bing Maps key. Higher resolution data is available when using an Enterprise Bing Maps key, which is available from Microsoft or by licensing the professional version of the One World SDK for Unity.

**Comment by SimBlocks** [comment]
Hello, please confirm if you are still seeing this elevation issue with the latest code.

**Comment by cneumann** [comment]
Sorry, I would have to test with the latest code in order to comment. The problem did no longer occur at the time when I switched to an Enterprise Bing Maps key. Closing this until I have updated information.
